version: 2
jobs:
  build:
    working_directory: ~/flask_app
    docker:
      -  image: circleci/python:3.6.4
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"
      - run: 
          command: |
              sudo pip install pipenv
              pipenv install pytest
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run: 
          command: |
              pipenv run pytest static/dictogram_test.py
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1